### ISSUE TITLE
Implementation details

### ISSUE THREAD

**Issue by juliangaal** [lfreist/x-search#3]
Thanks for open sourcing you work.

You mentioned you implemented this as part of your thesis? Any way I could get access to that to understand the algorithmic details?

**Comment by lfreist** [comment]
Hi, thanks for your interest. The thesis is publicly available [here](https://ad-publications.cs.uni-freiburg.de/theses/Bachelor_Leon_Freist_2023.pdf). Section 5.3 (page 16 ff) might be what you are looking for. Feel free to ask if you have further questions regarding the implementation (its explained in a relative abstract way within the thesis).

**Comment by juliangaal** [comment]
ah, perfect, thank you!
